default:
  image: code.waarp.fr:5000/oci/build-base:latest

stages:
  - test

lint:
  stage: test
  script:
    - echo "protected=$CI_COMMIT_REF_PROTECTED"
    - ls -la /cache/apps/gateway/gateway/ 2>/dev/null
    - nproc
    - go env GOMAXPROCS
    - cat /sys/fs/cgroup/cpu.max
  cache:
    - key: go_dependencies_cache
      paths:
        - $GOPATH
      when: always
    - key: $CI_COMMIT_REF_SLUG
      paths:
        - $GOLANGCI_LINT_CACHE
      when: always
