#!/usr/bin/env bash

ACTION=$1
shift

#####################################################################
###  TASKS
#####################################################################

t_test() {
    go test $@ ./cmd/... ./pkg/...
}

t_check() {
    local CI_VERSION=$(grep GOLANGCI_LINT_VERSION .gitlab-ci.yml | head -n 1 | cut -d' ' -f4)
    if ! $(which golangci-lint >/dev/null 2>&1); then
        echo "golangci-lint cannot be found. Please, install it and re-run checks"
        return 1
    fi
    if ! $(golangci-lint --version | grep $CI_VERSION >/dev/null 2>&1); then
        echo "***********************************************"
        echo "WARNING"
        echo "***********************************************"
        echo "Your version os golangci-lint is: $(golangci-lint --version | sed 's:.*\s\([0-9\.]\+\)\s.*:\1:')"
        echo "CI runs version $CI_VERSION"
        echo "***********************************************"
    fi
    go vet ./cmd/... ./pkg/...
    golangci-lint run \
        --enable bodyclose,dogsled,dupl,funlen,gocognit,gocyclo,gofmt,goimports,golint,gosec,misspell,nakedret,scopelint,stylecheck,unconvert,unparam \
        --max-issues-per-linter 0 --max-same-issues 0 \
        --exclude-use-default=false  \
        --exclude 'Potential file inclusion via variable' \
        --exclude 'Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked' \
        --exclude 'SA5008' \
        --skip-dirs .gocache \
        --exclude 'ST1016.*tec' \
        --tests=false --no-config
    # The exclude of 'ST1016.*tec' is needed to avoid false positives caused by stylecheck
    # not ignoring generated files (https://github.com/golangci/golangci-lint/issues/846)
    # In this case, it does not ignores a file generated by stringer
}

t_test_watch() {
    goconvey -launchBrowser=false -port=8081 -excludedDirs=doc $@
}

t_doc() {
    cd doc
    .venv/bin/sphinx-build source/ build/html/
}

t_doc_watch() {
    cd doc
    . .venv/bin/activate
    .venv/bin/sphinx-autobuild -p 8082 source/ build/html/
}

t_build() {
  mkdir -p build
  go build -o build/waarp-gateway ./cmd/waarp-gateway
  go build -o build/waarp-gatewayd ./cmd/waarp-gatewayd
}

build_static_binaries() {
  echo "==> building for $GOOS/$GOARCH"

  CGO_ENABLED=1 go build -ldflags '-s -w -extldflags "-fno-PIC -static"' \
    -buildmode pie \
    -tags 'osusergo netgo static_build sqlite_omit_load_extension' \
    -o "build/waarp-gateway_${GOOS}_${GOARCH}" ./cmd/waarp-gateway
  CGO_ENABLED=1 go build -ldflags '-s -w -extldflags "-fno-PIC -static"' \
    -buildmode pie \
    -tags 'osusergo netgo static_build sqlite_omit_load_extension' \
    -o "build/waarp-gatewayd_${GOOS}_${GOARCH}" ./cmd/waarp-gatewayd
}

t_build_dist() {
  cat <<EOW
This procedure will build static stripped binaries for Linux (32 and 64 bits)
and Windows (32 and 64 bits).

Warning:
  It needs a gcc compiler for linux 32bits (in archlinux, the package
  "lib32-gcc") and for Windows ()
EOW
  
  mkdir -p build
  GOOS=linux GOARCH=amd64 build_static_binaries
  GOOS=linux GOARCH=386 build_static_binaries
}


t_usage() {
    echo "Usage $0 [ACTION]"
    echo ""
    echo "Available actions"
    echo ""
    echo "  build       Builds binaries"
    echo "  build dist  Builds binaries for distribution"
    echo "  check       Run static analysis"
    echo "  test        Run tests"
    echo "  test watch  Starts convey to watch code and run tests when"
    echo "              it has been changed"
    echo "  doc         Builds the doc"
    echo "  doc watch   Watch the source of the documentation and builds it when"
    echo "              it has been changed"
    echo ""
}

#####################################################################
###  MAIN
#####################################################################

case $ACTION in
    build)
        SUB=$1
        case $SUB in
          dist)
            shift
            t_build_dist
            ;;

          *)
            t_build
            ;;
        esac
      ;;

    check)
        t_check
        ;;

    test)
        SUB=$1
        case $SUB in
            watch)
                shift
                t_test_watch $@
                ;;
            *)
                t_test $@
                ;;
        esac
        ;;

    doc)
        SUB=$1
        case $SUB in
            watch)
                shift
                t_doc_watch $@
                ;;
            *)
                t_doc $@
                ;;
        esac
        ;;

    *)
        t_usage
        ;;
esac
