// Code generated by "stringer -type=sqlTypeCode"; DO NOT EDIT.

package migration

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[nullType-0]
	_ = x[boolean-1]
	_ = x[tinyint-2]
	_ = x[smallint-3]
	_ = x[integer-4]
	_ = x[bigint-5]
	_ = x[float-6]
	_ = x[double-7]
	_ = x[varchar-8]
	_ = x[text-9]
	_ = x[date-10]
	_ = x[timestamp-11]
	_ = x[timestampz-12]
	_ = x[binary-13]
	_ = x[blob-14]
}

const _sqlTypeCode_name = "nullTypebooleantinyintsmallintintegerbigintfloatdoublevarchartextdatetimestamptimestampzbinaryblob"

var _sqlTypeCode_index = [...]uint8{0, 8, 15, 22, 30, 37, 43, 48, 54, 61, 65, 69, 78, 88, 94, 98}

func (i sqlTypeCode) String() string {
	if i >= sqlTypeCode(len(_sqlTypeCode_index)-1) {
		return "sqlTypeCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _sqlTypeCode_name[_sqlTypeCode_index[i]:_sqlTypeCode_index[i+1]]
}
