// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"fr": &dictionary{index: frIndex, data: frData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"About":               0,
	"About Waarp Gateway": 1,
	"Administration":      19,
	"Automation":          12,
	"Built on:":           4,
	"Code repository":     23,
	"Connectivity":        8,
	"Cryptography":        14,
	"Documentation":       21,
	"Email":               15,
	"Enter your credentials to access the Gateway": 28,
	"Enter your password":                          32,
	"Enter your username":                          30,
	"Home":                                         7,
	"Internal database error.":                     25,
	"Invalid credentials.":                         26,
	"Local clients":                                10,
	"Local servers":                                9,
	"Login":                                        27,
	"Monitoring":                                   16,
	"Password":                                     31,
	"Professional support":                         24,
	"Remote partners":                              11,
	"Rules":                                        13,
	"Runtime:":                                     5,
	"SNMP":                                         18,
	"Sign in":                                      33,
	"Transfers":                                    17,
	"Username":                                     29,
	"Users":                                        20,
	"Version:":                                     3,
	"Waarp Gateway and the Waarp logo are trademarks of Waarp SAS.":                             6,
	"Waarp Gateway is distributed under the terms of the [hyperlink]GPLv3 license[/hyperlink].": 2,
	"Website": 22,
}

var enIndex = []uint32{ // 35 elements
	// Entry 0 - 1F
	0x00000000, 0x00000006, 0x0000001a, 0x00000074,
	0x0000007d, 0x00000087, 0x00000090, 0x000000ce,
	0x000000d3, 0x000000e0, 0x000000ee, 0x000000fc,
	0x0000010c, 0x00000117, 0x0000011d, 0x0000012a,
	0x00000130, 0x0000013b, 0x00000145, 0x0000014a,
	0x00000159, 0x0000015f, 0x0000016d, 0x00000175,
	0x00000185, 0x0000019a, 0x000001b3, 0x000001c8,
	0x000001ce, 0x000001fb, 0x00000204, 0x00000218,
	// Entry 20 - 3F
	0x00000221, 0x00000235, 0x0000023d,
} // Size: 164 bytes

const enData string = "" + // Size: 573 bytes
	"\x02About\x02About Waarp Gateway\x02Waarp Gateway is distributed under t" +
	"he terms of the [hyperlink]GPLv3 license[/hyperlink].\x02Version:\x02Bui" +
	"lt on:\x02Runtime:\x02Waarp Gateway and the Waarp logo are trademarks of" +
	" Waarp SAS.\x02Home\x02Connectivity\x02Local servers\x02Local clients" +
	"\x02Remote partners\x02Automation\x02Rules\x02Cryptography\x02Email\x02M" +
	"onitoring\x02Transfers\x02SNMP\x02Administration\x02Users\x02Documentati" +
	"on\x02Website\x02Code repository\x02Professional support\x02Internal dat" +
	"abase error.\x02Invalid credentials.\x02Login\x02Enter your credentials " +
	"to access the Gateway\x02Username\x02Enter your username\x02Password\x02" +
	"Enter your password\x02Sign in"

var frIndex = []uint32{ // 35 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000a, 0x00000025, 0x0000007f,
	0x00000089, 0x00000097, 0x000000a1, 0x000000ea,
	0x000000f2, 0x00000100, 0x00000110, 0x0000011f,
	0x00000134, 0x00000143, 0x0000014b, 0x00000159,
	0x0000015f, 0x0000016b, 0x00000176, 0x0000017b,
	0x0000018a, 0x00000197, 0x000001a5, 0x000001ae,
	0x000001be, 0x000001d4, 0x000001fb, 0x00000213,
	0x00000224, 0x00000258, 0x0000026a, 0x00000289,
	// Entry 20 - 3F
	0x00000296, 0x000002b0, 0x000002bd,
} // Size: 164 bytes

const frData string = "" + // Size: 701 bytes
	"\x02À propos\x02À propos de Waarp Gateway\x02Waarp Gateway est distribué" +
	"e sous les termes de la [hyperlink]licence GPLv3[/hyperlink].\x02Version" +
	" :\x02Compilé le :\x02Runtime :\x02Waarp Gateway et le logo Waarp sont d" +
	"es marques déposées de Waarp SAS.\x02Accueil\x02Connectivité\x02Serveurs" +
	" locaux\x02Clients locaux\x02Partenaires distants\x02Automatisation\x02R" +
	"ègles\x02Cryptographie\x02Email\x02Supervision\x02Transferts\x02SNMP" +
	"\x02Administration\x02Utilisateurs\x02Documentation\x02Site Web\x02Dépôt" +
	" de code\x02Support professionnel\x02Erreur interne de la base de donnée" +
	"s.\x02Identifiants invalides.\x02Authentification\x02Entrez vos identifi" +
	"ants pour accéder à la Gateway\x02Nom d'utilisateur\x02Entrez votre nom " +
	"d'utilisateur\x02Mot de passe\x02Entrez votre mot de passe\x02Se connect" +
	"er"

	// Total table size 1602 bytes (1KiB); checksum: 28CA42C8
