package model

const (
	NameCredentials                 = "credential"
	NameAuthority                   = "authentication authority"
	NameAuthHost                    = "authority host"
	NameLocalAgent                  = "server"
	NameRemoteAgent                 = "partner"
	NameLocalAccount                = "local account"
	NameRemoteAccount               = "remote account"
	NameClient                      = "client"
	NameHistory                     = "history entry"
	NameTransfer                    = "transfer"
	NameNormalizedTransfer          = "normalized transfer"
	NameRule                        = "rule"
	NameRuleAccess                  = "rule permission"
	NameTask                        = "task"
	NameTransferInfo                = "transfer info"
	NameUser                        = "user"
	NameCryptoKey                   = "cryptographic key"
	NameEmailTemplate               = "email template"
	NameSMTPCredential              = "smtp credential"
	NameEbicsHost                   = "ebics host"
	NameEbicsSubscriber             = "ebics subscriber"
	NameEbicsSubscriberKeyMaterial  = "ebics subscriber key material"
	NameEbicsBankKey                = "ebics bank key"
	NameEbicsContractView           = "ebics contract view"
	NameEbicsContractViewItem       = "ebics contract view item"
	NameEbicsStandardBTFCatalog     = "ebics standard BTF catalog"
	NameEbicsStandardBTFEntry       = "ebics standard BTF entry"
	NameEbicsPayloadProfile         = "ebics payload profile"
	NameEbicsOperation              = "ebics operation"
	NameEbicsTransaction            = "ebics transaction"
	NameEbicsTransactionSegment     = "ebics transaction segment"
	NameEbicsNonce                  = "ebics nonce"
	NameEbicsKeyLifecycle           = "ebics key lifecycle"
	NameEbicsInitializationWorkflow = "ebics initialization workflow"
	NameEbicsRTNEvent               = "ebics RTN event"
	NameEbicsRTNProvider            = "ebics RTN provider"
	NameEbicsRuntimePolicy          = "ebics runtime policy"
	NameEbicsContractRefreshPolicy  = "ebics contract refresh policy"
	NameEbicsHistoryEntry           = "ebics history entry"
)

const authPassword = "password"
