package model

const (
	NameCredentials           = "credential"
	NameAuthority             = "authentication authority"
	NameAuthHost              = "authority host"
	NameLocalAgent            = "server"
	NameRemoteAgent           = "partner"
	NameLocalAccount          = "local account"
	NameRemoteAccount         = "remote account"
	NameClient                = "client"
	NameHistory               = "history entry"
	NameTransfer              = "transfer"
	NameNormalizedTransfer    = "normalized transfer"
	NameRule                  = "rule"
	NameRuleAccess            = "rule permission"
	NameTask                  = "task"
	NameTransferInfo          = "transfer info"
	NameUser                  = "user"
	NameCryptoKey             = "cryptographic key"
	NameEmailTemplate         = "email template"
	NameSMTPCredential        = "smtp credential"
	NameEbicsHost             = "ebics host"
	NameEbicsSubscriber       = "ebics subscriber"
	NameEbicsBankKey          = "ebics bank key"
	NameEbicsContractView     = "ebics contract view"
	NameEbicsContractViewItem = "ebics contract view item"
	NameEbicsPayloadProfile   = "ebics payload profile"
)

const authPassword = "password"
