// Code generated by "stringer -type TransferErrorCode"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TeOk-0]
	_ = x[TeUnknown-1]
	_ = x[TeInternal-2]
	_ = x[TeUnimplemented-3]
	_ = x[TeConnection-4]
	_ = x[TeConnectionReset-5]
	_ = x[TeUnknownRemote-6]
	_ = x[TeExceededLimit-7]
	_ = x[TeBadAuthentication-8]
	_ = x[TeDataTransfer-9]
	_ = x[TeIntegrity-10]
	_ = x[TeFinalization-11]
	_ = x[TeExternalOperation-12]
	_ = x[TeStopped-13]
	_ = x[TeCanceled-14]
	_ = x[TeFileNotFound-15]
	_ = x[TeForbidden-16]
	_ = x[TeBadSize-17]
	_ = x[TeShuttingDown-18]
	_ = x[endoferrorcodes-19]
}

const _TransferErrorCode_name = "TeOkTeUnknownTeInternalTeUnimplementedTeConnectionTeConnectionResetTeUnknownRemoteTeExceededLimitTeBadAuthenticationTeDataTransferTeIntegrityTeFinalizationTeExternalOperationTeStoppedTeCanceledTeFileNotFoundTeForbiddenTeBadSizeTeShuttingDownendoferrorcodes"

var _TransferErrorCode_index = [...]uint16{0, 4, 13, 23, 38, 50, 67, 82, 97, 116, 130, 141, 155, 174, 183, 193, 207, 218, 227, 241, 256}

func (i TransferErrorCode) String() string {
	if i >= TransferErrorCode(len(_TransferErrorCode_index)-1) {
		return "TransferErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TransferErrorCode_name[_TransferErrorCode_index[i]:_TransferErrorCode_index[i+1]]
}
