// Code generated by "stringer -type=sqlTypeCode"; DO NOT EDIT.

package migration

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[nullType-0]
	_ = x[internal-1]
	_ = x[boolean-2]
	_ = x[tinyint-3]
	_ = x[smallint-4]
	_ = x[integer-5]
	_ = x[bigint-6]
	_ = x[float-7]
	_ = x[double-8]
	_ = x[varchar-9]
	_ = x[text-10]
	_ = x[date-11]
	_ = x[timestamp-12]
	_ = x[timestampz-13]
	_ = x[binary-14]
	_ = x[blob-15]
}

const _sqlTypeCode_name = "nullTypeinternalbooleantinyintsmallintintegerbigintfloatdoublevarchartextdatetimestamptimestampzbinaryblob"

var _sqlTypeCode_index = [...]uint8{0, 8, 16, 23, 30, 38, 45, 51, 56, 62, 69, 73, 77, 86, 96, 102, 106}

func (i sqlTypeCode) String() string {
	if i >= sqlTypeCode(len(_sqlTypeCode_index)-1) {
		return "sqlTypeCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _sqlTypeCode_name[_sqlTypeCode_index[i]:_sqlTypeCode_index[i+1]]
}
